services:
  - type: web
    name: zyroai
    env: python
    region: singapore
    plan: free
    # CRITICAL: This single line forces all build steps in order
    buildCommand: "pyenv install 3.11.8 -s && pyenv global 3.11.8 && apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-ben poppler-utils ffmpeg && pip install --upgrade pip && pip install -r requirements.txt && mkdir -p uploads"
    startCommand: "gunicorn app:app"
    envVars:
      # CRITICAL: REMOVE the PYTHON_VERSION variable to prevent conflict
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
