services:
  - type: web
    name: zyroai
    env: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false